"""Dictionaries of Divoom Pixoo effect names to internal id's.

These were reverse engineered from the different Divoom Pixoo dials, clocks, channels ...
We keep them here hard coded for performance reasons.

These are actually managed by divoom using its online system, so they might need to be updated from time to time.

"""

from bidict import frozenbidict

"""
http://docin.divoom-gz.com/web/#/5/31
"""
CHANNEL_DICT: frozenbidict[str, int] = frozenbidict({
    'Black': 4,
    'Cloud': 1,
    'Custom': 3,
    'Faces': 0,
    'Visualizer': 2,
})

"""
http://docin.divoom-gz.com/web/#/5/27
http://docin.divoom-gz.com/web/#/5/28
"""
CHANNEL_INDEX_FACES_DICT: frozenbidict[str, int] = frozenbidict({
    'Custom - Clock Collections': 3,
    'Custom - DIY Analog Clock': 283,
    'Custom - DIY Digit Pic Clock': 285,
    'Custom - DIY Digital Clock': 284,
    'Custom - DIY Net Data Clock': 310,
    'Game - Brawl Stars': 1063,
    'Game - Chess': 1062,
    'Game - Clash Royale': 1059,
    'Game - Clash of Clans': 1060,
    'Game - DOTA 2': 1061,
    'Game - Fortnite': 208,
    'Game - League of Legends': 90,
    'Game - Overwatch': 92,
    'Game - PUBG': 696,
    'HOLIDAYS - Anniversary Countdown': 924,
    'HOLIDAYS - Anniversary Green': 878,
    'HOLIDAYS - Anniversary Pink': 880,
    'HOLIDAYS - Birthday countdown': 926,
    'HOLIDAYS - Christmas calendar': 902,
    'HOLIDAYS - Christmas clock1': 864,
    'HOLIDAYS - Christmas clock2': 940,
    'HOLIDAYS - Christmas girl room clock': 938,
    'HOLIDAYS - Happy New Year': 930,
    'HOLIDAYS - Heart-pounding time': 976,
    'HOLIDAYS - Heart-pounding time2': 1055,
    'HOLIDAYS - Shiba Inu Christmas': 904,
    'Nature&Weather - Azure gradient': 946,
    'Nature&Weather - Big Time': 882,
    'Nature&Weather - Chameleon clock': 136,
    'Nature&Weather - Chameleon clock-64': 896,
    'Nature&Weather - CyberChrono': 956,
    'Nature&Weather - Digital Frame': 908,
    'Nature&Weather - DigitalMeteo': 960,
    'Nature&Weather - Graffiti time': 856,
    'Nature&Weather - Green Neon Chic': 952,
    'Nature&Weather - LCD-Concept1': 968,
    'Nature&Weather - Pinkclock': 966,
    'Nature&Weather - Purple Neon Chic': 954,
    'Nature&Weather - Purple orange moment': 858,
    'Nature&Weather - Red Neon Chic': 950,
    'Nature&Weather - Retro web cute pastel': 970,
    'Nature&Weather - Shiba Inu clock': 920,
    'Nature&Weather - StickFamily': 964,
    'Nature&Weather - Tourmaline clock': 942,
    'Nature&Weather - Valoub Clock': 146,
    'Nature&Weather - Vital Sprout Clock': 980,
    'Nature&Weather - Weather ONE': 182,
    'Nature&Weather - Weather TWO': 916,
    'Nature&Weather - pink design clock': 918,
    'Normal - 35W Power': 1022,
    'Normal - 65W Power': 1021,
    'Normal - Analog': 1012,
    'Normal - Automation clock': 862,
    'Normal - Black Pink': 962,
    'Normal - Cassette player': 1005,
    'Normal - Celestial clock': 944,
    'Normal - Charging 1': 1009,
    'Normal - Charging 2': 1011,
    'Normal - Childlike Moments': 995,
    'Normal - Chinese Calendar': 1056,
    'Normal - Classic Digital Clock': 860,
    'Normal - Cloud Channel': 1006,
    'Normal - Custom 1': 1007,
    'Normal - Digital Frame': 180,
    'Normal - Digital Numbers': 1014,
    'Normal - Digital Tech': 998,
    'Normal - Digital dial 1': 830,
    'Normal - Dreamy Planets': 1001,
    'Normal - Flip Clock': 996,
    'Normal - Fluoro Gleam Clock': 978,
    "Normal - Girl's room clock": 912,
    'Normal - Hypnotic': 1015,
    'Normal - Kids Crayon': 948,
    'Normal - Lucky Casino Clock': 910,
    'Normal - Minimal Moment': 997,
    'Normal - Minimal Nightview 1': 1027,
    'Normal - Minimal Nightview 2': 1029,
    'Normal - Minimalist': 1016,
    'Normal - Mondrian Pixel Art': 872,
    'Normal - Nostalgic Beats': 1004,
    'Normal - Orange Pixel': 1018,
    'Normal - Oriental zodiac': 868,
    'Normal - Pixel City': 1002,
    'Normal - Plan': 1017,
    'Normal - Plush tiger and rainbow': 934,
    'Normal - Pointer dial 1': 831,
    'Normal - Retrclcok': 914,
    'Normal - Roman numeral Clock': 982,
    'Normal - Shiba Inu | Tiger': 932,
    'Normal - Smoothed Numbers': 1013,
    'Normal - Space Glitch': 999,
    'Normal - Spectrum Wave': 1003,
    'Normal - SunburstTime': 958,
    'Normal - Time(Neon)': 894,
    'Normal - Time(Sci-Fi)': 866,
    'Normal - Vibrant Colorblock': 1000,
    'Normal - Xenon lights': 994,
    'Normal - bun one clcok': 892,
    'Normal - bun two clcok': 888,
    'Normal - fluorescent green': 993,
    'Normal - iced lemonade clock': 884,
    'Normal - pixel display clock': 886,
    'Normal - sleeping kitty clock': 900,
    'Normal - wrist watch': 870,
    'Pixel Art - Cloud Channel': 992,
    'Pixel Art - Custom 1': 61,
    'Pixel Art - Custom 2': 986,
    'Pixel Art - Custom 3': 988,
    'Pixel Art - Custom1': 984,
    'Pixel Art - Custom3': 65,
    'Pixel Art - Visualizer': 990,
    'Plan - Plan1': 848,
    'Plan - Plan2': 849,
    'Plan - Plan3': 850,
    'Plan - Plan4': 851,
    'Plan - Plan5': 852,
    'Smart hardware - Fitbit clock': 202,
    'Smart hardware - HUAWEI health': 4,
    'Smart hardware - HypeRate': 1020,
    'Smart hardware - PC Monitor': 625,
    'Smart hardware - Pulsoid Dial': 846,
    'Social - Bilibili Account': 46,
    'Social - Bilibili Concept Account': 52,
    'Social - Bilibili Concept Video': 54,
    'Social - Bilibili Stream': 116,
    'Social - Bilibili Video': 114,
    'Social - Bilibili-works': 48,
    'Social - Divoom': 160,
    'Social - DouYu Stream': 58,
    'Social - Facebook Photo': 407,
    'Social - Facebook Video': 26,
    'Social - Influencer ': 102,
    'Social - New Twitch Account': 248,
    'Social - New Twitch Stream': 252,
    'Social - Pinterest': 665,
    'Social - TikTok User': 628,
    'Social - TikTok Video': 222,
    'Social - Tumblr': 666,
    'Social - Twitch Live List': 258,
    'Social - X- Account': 100,
    'Social - X- Post': 24,
    'Social - YouTube Account': 38,
    'Social - YouTube Account List': 55,
    'Social - YouTube Video': 40,
    'Social - YouTube Video List': 53,
    'Social - reddit': 664,
    'Sport - F1® Clock': 298,
    'Sport - MLB': 5,
    'Sport - NBA® Live Clock': 304,
    'Sport - NBA® Matches Clock': 292,
    'Sport - NBA® Teams Clock': 296,
    'Sport - NCAA LAX': 1024,
    'Sport - NHL': 602,
    'Sport - URFA® League Clock': 1025,
    'TOOLS -  Message Board(English only)': 874,
    'TOOLS - Amazon music': 188,
    'TOOLS - Barrage': 1054,
    'TOOLS - Custom RSS': 246,
    'TOOLS - Love notes': 928,
    'TOOLS - Pink Message Board': 876,
    'TOOLS - QR code': 282,
    'TOOLS - RSS Clock': 234,
    'TOOLS - Spotify Clock ': 186,
    'TOOLS - Vintage Message Board': 936,
    'TOOLS - World Clocks1': 72,
    'TOOLS - 世界时钟2': 1052,
    'Tivoo border - Frame 1': 792,
    'Tivoo border - Frame 10': 802,
    'Tivoo border - Frame 11': 803,
    'Tivoo border - Frame 12': 804,
    'Tivoo border - Frame 13': 805,
    'Tivoo border - Frame 14': 806,
    'Tivoo border - Frame 15': 807,
    'Tivoo border - Frame 2': 793,
    'Tivoo border - Frame 3': 794,
    'Tivoo border - Frame 4': 795,
    'Tivoo border - Frame 5': 796,
    'Tivoo border - Frame 6': 797,
    'Tivoo border - Frame 8': 800,
    'Tivoo border - Frame 9': 801,
    'Tivoo border - Frame7': 799,
    'Tivoo border - Rimless': 798,
    'Tivoo border - Widgets 1': 811,
    'Tivoo border - Widgets 10': 827,
    'Tivoo border - Widgets 11': 828,
    'Tivoo border - Widgets 12': 829,
    'Tivoo border - Widgets 2': 812,
    'Tivoo border - Widgets 3': 819,
    'Tivoo border - Widgets 4': 821,
    'Tivoo border - Widgets 5': 822,
    'Tivoo border - Widgets 6': 823,
    'Tivoo border - Widgets 7': 824,
    'Tivoo border - Widgets 8': 825,
    'Tivoo border - Widgets 9': 826,
    'financial - Bitcoin V2': 1032,
    'financial - CBOT': 1068,
    'financial - CME': 1067,
    'financial - COMEX': 1069,
    'financial - Cyber Currency': 206,
    'financial - Cyber Currency V2': 1033,
    'financial - Exchange Rate': 240,
    'financial - HK Stock-2': 1064,
    'financial - NYMEX': 1066,
    'financial - Stock - Detail': 1070,
    'financial - U.S. Stock - 2': 12,
    'financial - U.S. Stocks': 196,
})

"""
http://docin.divoom-gz.com/web/#/5/32
"""
CHANNEL_INDEX_CUSTOM_DICT: frozenbidict[str, int] = frozenbidict({
    'Custom 1': 0,
    'Custom 2': 1,
    'Custom 3': 2,
})

"""
http://docin.divoom-gz.com/web/#/5/33
"""
CHANNEL_INDEX_VISUALIZER_DICT: frozenbidict[str, int] = frozenbidict({
    'Blue bottom': 3,
    'Blue mirror': 9,
    'Dog on stage': 11,
    'Duck': 10,
    'EQ': 5,
    'Green bottom': 2,
    'Green mid': 6,
    'Green rain': 4,
    'Rainbow bottom': 7,
    'Rainbow line': 0,
    'Rainbow rain': 8,
    'Worm': 1,
})

"""
http://docin.divoom-gz.com/web/#/5/34
"""
CHANNEL_INDEX_CLOUD_DICT: frozenbidict[str, int] = frozenbidict({
    'Album': 3,
    'Favourite': 1,
    'Recommend gallery': 0,
    'Subscribe artist': 2,
})
